# Generated by Django 2.2.5 on 2019-09-10 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='desription',
            new_name='description',
        ),
    ]
